# "org" ensures this Service is used with the correct Serverless Framework Access Key.
org: kazu1216727
# "app" enables Serverless Framework Dashboard features and sharing them with other Services.
app: sample
# "service" is the name of this project. This will also be added to your AWS resource names.
service: sample

plugins:
  - serverless-api-gateway-throttling 

custom:
  apiGatewayThrottling:
    maxRequestsPerSecond: 10 
    maxConcurrentRequests: 5

provider:
  name: aws
  runtime: nodejs24.x
  architecture: arm64
  region: ap-northeast-1
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - ce:GetCostAndUsage
          Resource: "*"

build:
  esbuild:
    bundle: true
    format: cjs
    outExtension:
      '.js': '.cjs'

functions:
  hello:
    handler: handler.hello
  bye:
    handler: handler.bye
  sample: 
    handler: ./src/handler.sample
  costNotification:
    handler: ./src/costNotification.handler
    events:
      - schedule:
          rate: cron(0 0 * * ? *)
          enabled: true
    environment:
      SLACK_WEBHOOK_URL: ${ssm:udemy-aws-lamda-slack-webhook}
  helloWorld:
    handler: ./src/hello.handler
    events:
      - httpApi:
          method: get
          path: /hello

  taskPost:
    handler: ./src/taskHandler.post
    events:
      - httpApi:
          method: post
          path: /tasks
    iamRoleStatements:
      - Effect: Allow
        Action:
          - dynamodb:PutItem
        Resource: 'arn:aws:dynamodb:*:*:table/tasks'

resources:
  Resources:
    TasksDynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: tasks
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5